model:
  type: gcn
sparse: false
epochs_cls: 200
lr_cls: 0.001
w_decay_cls: 0.0005
hidden_dim_cls: 32
dropout_cls: 0.5
dropedge_cls: 0.75
n_layers_cls: 2
patience_cls: 10
epochs: 4000
lr: 0.01
wd: 5e-6
n_hidden: 512
n_embed: 256
n_proj: 256
dropout: 0.5
dropedge_rate: 0.5
n_layers: 2
type_learner: fgp
k: 30
sim_function: cosine
activation_learner: relu
eval_freq: 50
tau: 0.9999
maskfeat_rate_learner: 0.7
maskfeat_rate_anchor: 0.6
contrast_batch_size: 0
c: 0

training:
  patience: ~
  criterion: ~

dataset:
  feat_norm: false   # sublime does not normalize feats
  cora_split: false
  load_graph: false
  sparse: true

# analysis
analysis:
  save_graph: false
  save_graph_path: results/graph